vich_uploader:
    db_driver: orm

    mappings:
        properties:
            uri_prefix: '/images/properties'
            upload_destination: '%kernel.project_dir%/public/images/properties'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
